[project]
name = "ballsdex-achievements"
version = "1.2.2"

description = "Achievement package for Ballsdex 3.0"
authors = [
    { name = "Seif", email = "seiftheman1@gmail.com" },
]

[project.urls]
Repository = "https://github.com/seiftheman/ballsdex-achievements"
Documentation = "https://github.com/seiftheman/ballsdex-achievements#readme"
Issues = "https://github.com/seiftheman/ballsdex-achievements/issues"
