# Generated by Django 6.0 on 2026-07-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('achievement_emoji_id', models.BigIntegerField(blank=True, help_text='Discord emoji ID for achievement.', null=True)),
                ('description', models.TextField()),
                ('enable', models.BooleanField(default=True, help_text='Turn on or off the achievements.')),
                ('required_quantity', models.PositiveIntegerField(default=1, help_text='Number of each required combo (ball + special) needed')),
                ('self_catch', models.BooleanField(default=False, help_text='Whether this achievement needs self_catched balls')),
                ('required_balls', models.ManyToManyField(blank=True, help_text='Which countryballs you need to collect.', related_name='achievements', to='bd_models.ball')),
                ('reward', models.ManyToManyField(blank=True, help_text='rewards for achievements', related_name='achievements_reward', to='bd_models.ball')),
                ('special_required', models.ManyToManyField(blank=True, help_text='Any specials.', related_name='special_achievement', to='bd_models.special')),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='achievements.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='bd_models.player')),
            ],
            options={
                'verbose_name': 'Player Achievement',
                'verbose_name_plural': 'Player Achievements',
                'db_table': 'player_achievement',
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
